### ISSUE TITLE
Kadena CLI template data

### ISSUE THREAD

**Issue by EnoF** [kadena-community/kadena.js#2695]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The bug was not reported before
- [X] I am using the **latest version** of the relevant package(s)

### What operating system are you using? And what version?

Linux

### What package is the bug report about?

@kadena/kadena-cli

### Describe the bug

When generating a transaction using the following template:

```yaml
codeFile: token.pact
dataFile: data.yaml
publicMeta:
  chainId: "{{chainId}}"
  sender: "r:ns-operate-keyset"
  gasLimit: 80300
  gasPrice: 0.0000001
  ttl: 600
signers:
 - public: "fab92c47ccb1fdd25173e2981ebb29de989acea88792e34cc87298f6a1578842"
   caps: []
networkId: "testnet04"
type: exec
```

and the following data:

```yaml
chainId: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
```

I expect 20 transactions to be created as in kda-tools

### Steps to reproduce the behavior

See description

### What did you expect to happen?

See description

### Participation

- [X] I am willing to submit a pull request for this issue.
